---
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-10.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack--
            - stack-
            - stack-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: stack--
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint